istresearch/rapidpro

static/coffee/flows/services.coffee, static/coffee/flows/widgets.coffee
Flow Create Message broken when using subdir.
Prior to applying this patch:
1. Enable the subdir in the docker-compose.yml file SUB_DIR var.
2. Navigate the flow editor ex: /subdir/flow/editor/a69cf345-6729-4de8-83fc-7b90a1607c5c/
3. Click `Create Message` and you will notice that no modal dialog pops up.
4. Open the javascript console and you will see an error similar to:  `GET https://p35.dev.istresearch.com/partials/node_editor 404 (Not Found)`
After applying this fix, hard refresh the page and you should notice the modal dialog appears as expected.
=> PULSE-6863 - Flow Create Message broken when using subdir

temba/orgs/views.py, temba/settings_common.py, templates/includes/nav.haml
This PR adds a new form view accessible to the superuser for assigning users to an existing ORG without the email invitation workflow.
**Testing:**
1) Start RapidPro.
2) Go to `<base>/org/assign_user` when logging in as the RapidPro Superuser.
3) Select an organization, type in the username of an existing user, select the role for the user.
4) Submit the form.
5) Log in as the user and confirm access to the organization.
=> P4 457 - New view to assign user to organization

temba/orgs/views.py
When creating a new organization, the proxy needs to know the engage organization ID that was created. This PR exposes that ID value.
**Testing:**
1) Start RapidPro.
2) Go to `<base>/org/grant` when logged in as the RapidPro Superuser.
3) Create an organization, type in the username of an existing user
4) Submit the form.
5) A successful response should indicate the organization ID on the page.
=> P4 457 - Adding organization ID to form response

temba/channels/views.py
- change to use org name requires client-side change: P4-725
- will not affect older clients
=> P4-725 - Add org name to claim command response

temba/channels/models.py
- NOTE: I commented out the old email logic since I'm not sure what's preferred.. figured better to leave it than remove it in case we're merging in rapidpro's changes and wanted to know why it was removed.. but, either way works for me
=> PULSE-7012 - Default Android channel name to phone number and alert email to 'none'

templates/channels/channel_read_list.haml
- logic comes from @martinezah and is basically this:
- name, if set, otherwise the model, be displayed first, then the phone number after
- And if the name == phone number, treat it like the name's not set
=> P4-1021 - Fix Android channel display in home/list view

temba/channels/views.py, temba/middleware.py
Since `hasattr(settings, 'SUB_DIR'):` is always true even when settings.SUB_DIR is None, replace it with `if settings.SUB_DIR:` so that we protect the IF branch from crashing when SUB_DIR is None (not defined as an ENV var).
=> hasattr() always true for SUB_DIR.

temba/channels/types/bandwidth/views.py, temba/channels/types/bandwidth_international/views.py
Existing channels will need to have the name set to the address in the postgresql database prior to this fix working.
Essentially we're now duplicating the address into the channel.name field to avoid modifying any RP core files.
Moving forward if the account_sid is needed it should be retrieved from the channel.config['account_sid'] json field in posgres.
=> PULSE-7093 - Preferred channel in flow - The channel should display as "BWI: [senderID]"

templates/channels/channel_read_list.haml
Simple haml modification that will (hopefully) suffice.
The channel display should present as "[Bandwidth logo] BWI - [Sender ID]".
=> Pulse 7090

temba/channels/types/bandwidth_international/tests.py, temba/channels/types/bandwidth_international/views.py, temba/orgs/models.py, temba/orgs/views.py, templates/orgs/org_bandwidth_account.haml, templates/orgs/org_bandwidth_international_account.haml, templates/orgs/org_bandwidth_international_connect.haml
BWI account settings code tweaked to remove Account and App SIDs from its settings as only User/Pw is needed to connect to the BWI account.  This fixes most of the issues remaining in the https://github.com/istresearch/rapidpro/pull/62/ PR.  Last thing I have yet to figure out is to populate the user/pw fields with the decrypted information when you go back to edit the channel config.
Also, to test an actual BWI send/receive to ensure my changes didn't dork anything else up that was already working.
=> P4-1086 BWI tweaks

static/less/style.less, temba/channels/types/postmaster/type.py, temba/channels/types/postmaster/views.py
The edit channel page should now provide a dropdown that allows you to also update the scheme.
1. Navigate to: channels/types/postmaster/claim
2. Create a postmaster channel. 
3. Check the postgres database channels_channel table to ensure that the newly created channels schema is properly set: `select id, channel_type, schemes  from channels_channel where channel_type = 'PSM' and is_active is true;`
4. Now navigate to the channel's update page ex (channels/channel/update/[channel_id]/).
5. Modify the scheme and save the changes.
6. Verify in the postgres channels_channel table that the channels scheme has been updated: `select id, channel_type, schemes  from channels_channel where channel_type = 'PSM' and is_active is true;`
=> postmaster - Schemes field updates

templates/channels/channel_read_list.haml
just removing the enable bulk sending button from the orgs/home page by removing it from the read_list.
To test, add a channel that supports bulk sending such as an android device.
Before:
After:
=> P4-801 - Remove 'Enable Bulk Sending' from the Channel Options

temba/orgs/views.py, templates/orgs/org_bandwidth_account.haml, templates/orgs/org_bandwidth_international_account.haml, templates/orgs/org_postmaster_account.haml
1. Create a BWI account using a valid BWI dashboard username and password (sorry about that last time, @baracudda). 
2. Create a BWI channel by providing a sender name and sender type.
3. Navigate to the org/home page and locate the bandwidth international account (not the channel).
4. Click on the account to expand the credentials form and then click on the "_disconnect your bandwidth international account_" link.
5. Click the "disconnect" button on the dialog
**Expected Result:**
The account will be unlinked from the Org and you will be redirected to the Org home screen.
=> P4-1383 - Bug - removing a channel redirects to the wrong page

temba/flows/views.py
The new flow editor is used regardless of selection. This PR removes the form filed from the dialog.
<Concise sentence describing change>The new flow editor is used regardless of selection, so removing the form field from the dialog.
<Description for Techops of how to handle changes>None.
1. Go to https://engage.dev.istresearch.com/flow/
2. Create a new flow. The dialog for a new flow should no longer contain a drop down for the Flow Editor Type.
3. Validate your new flow open in the new flow editor.
=> P4 1399 - Removing flow editor choice from new flow dialog (develop)

temba/flows/views.py
The new flow editor is used regardless of selection. This PR removes the form filed from the dialog.
<Concise sentence describing change>The new flow editor is used regardless of selection, so removing the form field from the dialog.
<Description for Techops of how to handle changes>None.
1. Go to https://engage.dev.istresearch.com/flow/
2. Create a new flow. The dialog for a new flow should no longer contain a drop down for the Flow Editor Type.
3. Validate your new flow open in the new flow editor.
=> P4 1399 - Removing flow editor choice from new flow dialog (master)

temba/ext/api/v2/views.py
**Note:** _Included in this PR is a commit that changes the serialization of the config object into a nested json object instead of json string._
Removing channels via the Extended REST API via CURL.
**Method:** DELETE
**Required Headers:** "Authorization: Token zyxponmlyabadabadoo"
**Path:** /ext/api/v2/channels.json?uuid=UUID_OF_CHANNEL_TO_BE_DELETED
**Example:**
`curl -vvv -H "accept: application/json" -H 'Cache-Control: no-cache' -H "Authorization: Token e90c28b089cfc9542a1351d8f36619f5a70e1771" -X DELETE "https://83f83d51.ngrok.io/engage/ext/api/v2/channels.json?uuid=993f1212-db36-0528-cd32-e0f93a75fad4"`
**Results:**
1) If the channel exists and is released OR if the channel exists yet an exception is thrown while attempting to release, you will receive a response object:
`{"name": …
=> P4-1356 - Engage - New API endpoint to remove Postmaster channels

temba/channels/types/postmaster/type.py, temba/channels/types/postmaster/views.py, temba/contacts/models.py
Introducing New Postmaster specific Channel Schemes for contacts.
The contact's update form now has 4 additional schemes:
```
(PM_WHATSAPP_SCHEME, _("Postmaster WhatsApp identifier"), PM_WHATSAPP_SCHEME),
(PM_TELEGRAM_SCHEME, _("Postmaster Telegram identifier"), PM_TELEGRAM_SCHEME),
(PM_SIGNAL_SCHEME, _("Postmaster Signal identifier"), PM_SIGNAL_SCHEME),
(PM_LINE_SCHEME, _("Postmaster Line identifier"), PM_LINE_SCHEME),
```
This PR also includes a fix to the Postmaster channel update server-side submission logic where we now update the chat_mode based on the scheme:
```
def save(self, commit=True):
config = self.object.config
config[Channel.CONFIG_CHAT_MODE] = self.cleaned_data['schemes'][0]
return super().save(commit=commit)
```
1. To test, create a Postmaster channel with any chat_mode. …
=> P4-1457 - Engage - New Postmaster Channel Schemes

temba/channels/types/postmaster/views.py
P4-1457 - Fixing postmaster sms scheme bug
There was a bug caused by the lack of the SMS_SCHEME having a PM_ prefix. 
Added a special condition so that if the chat mode is SMS then we will use the built in SMS scheme. Otherwise we will use the PM_ specific schemes.
None.
=> P4-1457 - Fixing postmaster sms scheme bug

temba/channels/models.py, temba/channels/types/postmaster/postoffice.py, temba/channels/types/postmaster/views.py, temba/ext/api/v2/views.py, temba/orgs/models.py, temba/orgs/views.py, templates/channels/types/postmaster/claim.haml
https://istresearch.atlassian.net/browse/P4-1355
New input fields for postmaster form creation along with the option to scan a QR code dynamically retrieved from the postoffice REST API.
1) Ensure that you have added valid postoffice api credentials to your settings.py
2) Standup the P4 Engage environment **that includes the latest Postoffice**
3) Navigate to …
=> P4-1355 - Postmaster New Channel page to display claim code

temba/channels/types/postmaster/views.py
Postmaster channel names were getting reused for each mode for a specific device. This led to confusion anywhere the names were used without any extra context of which channel was which mode. This PR appends the scheme used to the name, for example: `mydevice [pm_telegram]`
Postmaster channel names will be appended with the channel scheme for easy identification. 
None
- **Features and Alerting**: Required.
- **P4 Alerting**: Required.
1. Initialize a full engage stack
2. Generate a claim code for postmaster on the new channel page, and connect the channel
3. For any active modes, all channels …
=> P4-1518 - Add postmaster channel scheme as suffix to the name

temba/msgs/views.py
Simple change that allows you to delete messages from the messages failed messages tab.
Simple change that allows you to delete messages from the messages failed messages tab.
N/A
Standup Engage and navigate to the messages page and then click on the failed link (tab).
You must have previously failed messages present to see this feature, but if present then you will be able to select a message and then delete it using the …
=> P4-1418 - adding delete functionality to the failed messages tab

templates/flows/flow_editor_next.haml
Z-index to ensure that the Org select dropdown menu still works while viewing the flow editor page.
Modified the z-index of the .org-header .pull-right classes to ensure the click events fire when the org menu icon is clicked from the flow editor page
See the gif image here: https://istresearch.atlassian.net/browse/P4-1521
Ensure that the ORG …
=> P4-1521 - Engage - Org selector menu not available from flow edit page

temba/contacts/models.py, temba/contacts/templatetags/contacts.py
Added Postmaster VK channel and scheme
Added Postmaster VK support to engage
None.
Image: `istresearch/p4-engage:ci-4.0.3-P4-1658`
1. Spin up an entire 4.0.3-dev engage stack, using a mailroom with `pm_vk` added as a scheme to `MAILROOM_CUSTOM_SCHEMES`
2. Add/register a postmaster channel using VK Mode
3. Ensure that you can create a new contact using a `Postmaster VK ` identifier. 
4. Ensure that you can send messages to the contact using a `Update Contact`->`Channel` node  in a flow. 
5. …
=> P4-1658 - Add VK mode to postmaster channel

temba/settings_common.py
Engage - Send Message Button Requires Admin
Reverting existing changes to settings_common.py Editor permissions due to a bug that requires Editors to have channel_claim roles to broadcast messages.
Adding channel_claim role to Editors
N/A
See https://istresearch.atlassian.net/browse/P4-1689 for bug details.
Be sure to run `manage.py makemigrations` &  `manage.py migrate --run-syncdb` to apply the DB changes.
=> P4-1689 - Reverting Editors channel_claim revocation

temba/msgs/models.py, temba/settings_common.py
P4-1736 - Turning `MAX_ORG_LABELS` into a configurable setting.
`MAX_ORG_LABELS` is now a configurable setting.
`MAX_ORG_LABELS` is now configurable via environment variable `MAX_ORG_LABELS`. The default value is coded in rp-docker/settings*.py
Pre 4.0.3
See companion PR in
=> P4-1736 - Engage - Configurable Label Count Limit

temba/contacts/models.py, temba/contacts/templatetags/contacts.py
Added support for Viber and Line postmaster modes
Line and Viber postmaster modes can now be registered.
None.
1. Register a new postmaster line and viber channel. An example curl is below to manually register a channel using the add channel endpoint. Replace `chat_mode=VB` with `chat_mode=LN` to register a line channel.
```
curl --location --request POST 'http://localhost:8001/ist/ext/api/v2/channels.json?type=PSM&device_id=123&chat_mode=VB&device_name=tester&claim_code=YOUR_CLAIMCODE_HERE …
```
=> P4-1815, P4-1816 - Viber and Line modes for Postmaster

temba/contacts/models.py, temba/contacts/templatetags/contacts.py
Add twitter scheme to postmaster channel. 
A new postmaster twitter URN scheme has been added
None.
1. Register a new postmaster twitter channel. An example curl is below to manually register a channel using the add channel endpoint. 
```
curl --location --request POST 'http://localhost:8001/ist/ext/api/v2/channels.json?type=PSM&device_id=123&chat_mode=TWTR&device_name=tester&claim_code=YOUR_CLAIMCODE_HERE&org_id=1' \
--header 'Authorization: Token ENGAGE_SUPERADMIN_TOKEN'
```
2. Ensure …
=> P4-1885 - Add twitter scheme for PM channels

temba/api/v2/serializers.py
Enables deleting Failed messages via the Rest API.
Enables deleting Failed messages via the Rest API.
N/A
1. Standup Engage 4.0.x
2. Send a message to the Inbox -> Failed queue.
3. Navigate to /msg/failed/
4. Fetch the message ID from the database:
`select id from msgs_msg where text = '{YOUR MSGS TEXT.}';`
5. Run: `curl -X POST -H "Authorization: …
=> P4-1419 - Engage - Delete Messages from Failed box (API)

temba/channels/types/postmaster/type.py, temba/channels/types/telegram/type.py, temba/channels/types/twitter/views.py, temba/channels/types/viber_public/views.py, temba/channels/views.py
P4-1347 - Engage: Implement fine-grained throttles on external API calls
Exposes the TPS (Transactions Per Second) variable in the Channel edit page. (Ex. engage/channels/channel/update/35/). Configuring this causes Engage to append the channels TPS value onto outgoing messages that are bound for the redis queue. (Ex. `4717) "msgs:9f3b4a81-ac44-4ffa-a295-02c34cdfe231|9:tps:1598380916"`)
Exposes the TPS (Transactions Per Second) variable in the Channel edit page. (Ex. engage/channels/channel/update/35/)
- **Features and …
=> P4-1347 - Engage: Implement fine-grained throttles on external API calls

temba/channels/urls.py, temba/channels/views.py, templates/channels/channel_read.haml
Engage P4-1963/ Courier P4-1934 GUI exposure of the kill-switch.
New Button to expose the new Courier kill-switch functionality along with code to gracefully handle errors.
Channel's now have a Purge Outbox kill-switch.
1. Standup Engage 4.0.x with the latest Courier dev from dockerhub since it supports this new purge (killswitch) …
=> P4-1963 - Engage/Courier channel purge/kill switch

temba/ext/api/v2/views.py
Allow PSM channel name updates via V2 API
- A PSM channel name can be updated If a UUID and device_name is provided to the v2 ext api.
None.
1. Add a PSM channel to engage.
2. Submit a request to update the channel name:
```
curl --location --request POST 'http://localhost:8001/ist/ext/api/v2/channels.json?type=PSM&device_id={DEVICE_ID}&device_name={NEW_DEVICE_NAME}&uuid={CHANNEL_UUID}' --header 'Authorization: Token {API_TOKEN}'
```
=> P4-1895 - Allow channel name updates via v2 api

temba/channels/views.py, templates/channels/channel_manage.haml
P4-2321 -  Manage Channels page filtering and sorting
Within the UI, the "manage channels" page should be searchable based on (at least) the channel UUID and name. Additionally, the header rows should be sortable. 
Added search filter and sorting for channel management page.
None.
1. Standup the Rapidpro prereqs. (ex. https://github.com/istresearch/postoffice/blob/develop/README.md)
2. Navigate to …
=> P4-2321 - Engage - Manage Channels page filtering and sorting

temba/msgs/models.py, temba/msgs/tests.py, temba/msgs/views.py, templates/msgs/label_delete.haml, templates/msgs/msg_filter.haml
P4-2423 -  Allow only deleting msg folders without active children labels.
Removed deleted folders from populating the create label dialog's parent folder selection menu.
Removed deleted folders from populating the create label dialog's parent folder selection menu.
None.
**Part 1:**
1. Standup an engage stack.
2. Navigate to the messages page.
3. Create a folder,
4. Click create label,  then under the folder drop …
=> Feature/p4 2423 - Allow only deleting msg folders without active children labels

templates/channels/types/postmaster/claim.haml
See P4-2488 - Redirect to channels.channel_manage?search=device_id
Ex. Upon Postmaster channel creation the form will redirect to channels/channel/manage/?search=358240051111110
Upon Postmaster channel creation the form will redirect to channels/channel/manage/?search=[address]
Upon Postmaster channel creation the form will redirect to channels/channel/manage/?search=[address]
None.
1. Standup Engage.
2. Create a postmasterr channel.
3. Ensure that you are redirected to the channel …
=> P4-2488 - Postmaster Channel Add Redirect to show New Channel

temba/channels/views.py
P4-2737 - Fixes Channel UpdateForm bug caused by null config fields.
P4-2737 - Fixes Channel UpdateForm bug caused by null config fields.
Fixed Channel UpdateForm bug caused by null config fields.
=> P4-2737 - null Config prevents saving channel information

temba/ivr/models.py
Requires mailroom PR: https://github.com/istresearch/mailroom/pull/22
P4-2678 - Add option to disable IVR Flow retry
Add option to disable IVR Flow retry
Add option to disable IVR Flow retry
N/A
1. Edit a flow and set Retry call if unable to connect to Never
2. Run the flow and reject the call so that it will be marked as Failed.
3. Wait to ensure that no retries are attempted.
1. Edit the same flow and set Retry to 30 minutes (Sorry, but I dont think we should add a test option for 1 …
=> P4-2678 - Engage - Voice Call Retry Disable

temba/channels/models.py, templates/channels/channel_read.haml
=> Revert the flow in use PR, put the warning back in place for now.

temba/channels/views.py
While working on 2999 I failed to remove country as a readonly field from the default channel  config.  This fixes that. 
The country field will be editable on any channels that have it. 
None.
1. `docker-compose up -d --build`
2. Edit the settings on a channel that uses the country field. 
3. The country field should be writeable.
=> P4-3035 - Remove country as readonly from default channel config

temba/contacts/views.py
Merge accidentally left out a required method from upstream.
Fixed Contact edit Custom Fields menu button giving a 500 error.
None.
Go to Staging and click on any Contact from any org you please to see contact details page. In hamberger menu, select "Custom Fields" and the popup dialog shows 500 error.
Do the same on Dev and it shows a drop down instead of an error.  The drop down is empty because there are no defined custom fields, but the main thing is there's no error for when someone …
=> P4-3464: Contact Custom Fields edit button 500 error

docker/Dockerfile.pyapp, docker/customizations/any/temba/channels/types/android/type.py, docker/customizations/any/temba/channels/views.py, docker/customizations/any/temba/settings_engage.py, docker/customizations/any/temba/urls.py, docker/customizations/any/templates/channels/channel_claim.haml, docker/customizations/engage/temba/settings.py, engage/api/__init__.py, engage/api/exceptions.py, engage/api/serializers.py, engage/channels/purge_outbox.py, engage/utils/__init__.py, engage/utils/logs.py, engage/utils/overrides.py, temba/channels/types/bandwidth_international/type.py, temba/channels/types/nexmo/is-now-vonage.txt, temba/ext/api/v2/views.py, templates/channels/types/postmaster/claim.haml
PostMaster claim code page now includes its data fields as <span>s with IDs in them for easy DOM parsing for RobotFramework.
Tweaks to help with automated QA.
None.
PM Claim Code page now lists the data fields without their label text as <spans> with IDs.
The values themselves will still need to be trimmed of whitespace; that is something built-in that cannot be removed so easily, but is not required since scripts …
=> P4-3161: add claim code spans with ids

docker/Dockerfile.pyapp, docker/customizations/any/temba/channels/types/android/type.py, docker/customizations/any/temba/channels/views.py, docker/customizations/any/temba/settings_engage.py, docker/customizations/any/temba/urls.py, docker/customizations/any/templates/channels/channel_claim.haml, engage/api/__init__.py, engage/api/exceptions.py, engage/api/serializers.py, engage/utils/__init__.py, engage/utils/logs.py, temba/channels/types/bandwidth_international/type.py, temba/channels/types/nexmo/is-now-vonage.txt, temba/ext/api/v2/views.py
Return 451 status on API calls with tokens from orgs that are out of credits.
Return the readily identifiable https status code 451 for when orgs need attention.
None.
Using a key from an org that is out of credits, call an API routine.
See the http status code return as 451 rather than 400.
e.g. Using Postman:
http://localhost/ext/api/v2/channels.json?type=PSM
header: Authorization: Token fe7ac1....
body data: {
"claim_code": "DEPRECATED",
"device_name": "fisch010",
"device_id": "bla123", …
=> P4-3500: add error log and 451 status if org suspended

docker/Dockerfile.pyapp, docker/customizations/any/temba/channels/types/android/type.py, docker/customizations/any/temba/channels/views.py, docker/customizations/any/temba/settings_engage.py, docker/customizations/any/templates/channels/channel_claim.haml, engage/utils/logs.py, temba/channels/types/bandwidth_international/type.py, temba/channels/types/nexmo/is-now-vonage.txt
Replacing Android Channel with Postmaster accidentally also hid some channels; unhide them.
Missing channels restored to the Add Channels page.
None.
https://engage.dev.istresearch.com/channels/channel/claim/
Add Channels page displays all the channels it should, again.  New area at top: Featured, which is always the PM channel. Also, Recommended channels are displayed again in their appropriate sections down below rather than their original "moved" condition. Show All Channels link at …
=> P4-3467: unhide vonage/twilio

docker/customizations/any/static/less/engage.less, docker/customizations/any/temba/msgs/views.py, docker/customizations/any/templates/contacts/contact_read.haml, engage/hamls/includes/org.haml, engage/hamls/msgs/message_box.haml, engage/msgs/__init__.py, engage/msgs/datepicker.py, engage/msgs/exporter.py, engage/msgs/inboxview.py, engage/utils/__init__.py, engage/utils/overrides.py, temba/msgs/views.py
Ticket for bug-that-was-not-a-bug, fixed:
Users with a single org have CSS similar to the org picker for contrast and visiblity.
Contact "Send via *" buttons now have tooltips as well as a group label.
Messages that contain HTML (email ads mostly) processed to remove problems like long strings of non-breaking spaces that will break the page being rendered too wide to view properly.
Visual polish applied, no functional changes in this PR.
None.
*Steps to test your application for someone …
=> P4-3568: various visual tweaks

engage/channels/tasks.py, temba/channels/tasks.py
Update PM channel last_seen timestamp with more quality control.
Last Seen timestamp for PostMaster channels more reliable now.
None.
Celery task for updating PostMaster channel last_seen datetimes now ensure the timestamp is more recent than what is saved and log errors should any occur (was Debug level before).
=> P4-2858: PM channel last_seen timestamp QC

docker/customizations/any/templates/frame.haml, engage/channels/tasks.py, temba/channels/tasks.py
Org picker should be at top of page even when no menus available.
Org picker now afixed to the top of page even when no menus available.
None.
On Dev instance:
1. ensure you have multiple org access
2. logout
3. login
4. while at the "org choose"  page with different buttons per org you belong to, ensure the org picker is at the top of the page (there should be no menus availabe apart from the ... and Logout).
=> P4-3665: ensure menu-area takes up full height even when no menus.

docker/customizations/any/temba/orgs/views.py, engage/channels/types/postmaster/download.py, engage/hamls/orgs/email/invitation_email.html, engage/utils/overrides.py, pyproject.toml, temba/api/models.py, temba/channels/types/postmaster/postoffice.py, temba/channels/types/postmaster/views.py, temba/settings_engage.py
If the old DL PM env vars are blank (for link and QRCode base64 definition) and the new Fetch PM vars are set, generate a random dl_pm url link and create the QRCode for it.
Download PM link randomly generated on container start.
None.
Download PM endpoint is now randomly generated on container start rather than be fixed and publicly available.
ALSO: Email invites use raw URL instead of an <a> HTML tag.
=> P4-3778: Download PM behind random link

engage/archives/models.py, engage/channels/models.py, engage/channels/views.py, engage/contacts/models.py, engage/msgs/inbox_msgfailed.py, engage/msgs/models.py, engage/msgs/views/inbox.py, engage/orgs/views/bandwidth.py, engage/orgs/views/create.py, engage/orgs/views/user_assign.py, engage/static/engage/js/broadcast_send.js, engage/utils/class_overrides.py, engage/utils/overrides.py
Failed inbox child class cannot find overridden method in super class; workaround generates an "orig_*" method callable from child class.
Fixed Failed Msg inbox so it does not generate an error.
None.
Messages tab, Failed area selected, you do not see a page that reads simply "Error 500".
=> P4-4185: Failed Msg inbox get 500 error

engage/archives/models.py, engage/channels/models.py, engage/contacts/models.py, engage/msgs/models.py, engage/static/engage/js/broadcast_send.js
Contact list selection Send Message did not have a confirmation dialog.
Contact list selection Send Message did not have a confirmation dialog.
None.
Send Messages buttons in:
Messages page
Contact page
Contact List page, when message checked
in all areas, send a message and Cancel/Send to ensure a confirmation dialog shows up and both options work as expected.
=> P4-4131: missing Send Msg confirmation box

engage/channels/models.py
When checking for TEL in channel schemes to auto-allow International Calls, ensure it is not None first. 
Fixed error when adding Nexmo(Vonage) and Twilio channels.
Test steps should now succeed for:
[Nexmo(Vonage) channel](https://istresearch.atlassian.net/projects/P4?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/P4-T290)
[Twilio Channel](https://istresearch.atlassian.net/projects/P4?selectedItem=com.atlassian.plugins.atla …
=> P4-4128 & P4-4130 & P4-4129: error NoneType is not iterable

engage/channels/models.py, engage/channels/types/vonage_client.py, engage/channels/types/vonage_views.py, engage/hamls/channels/channel_claim_number.haml, engage/hamls/orgs/user_list.haml, engage/msgs/views/inbox.py, engage/orgs/models.py, engage/orgs/views/user_delete.py, engage/orgs/views/user_list.py, engage/static/engage/less/engage.less, engage/utils/middleware.py, engage/utils/overrides.py, scm/utils.sh, temba/settings_engage.py
User list while logged in as superuser now lets you sort and search usernames/emails.
User list while logged in as superuser now lets you sort and search usernames/emails.
login as superuser, go to Users area and search / sort.
=> P4-3030: superuser user list search/sort

engage/contacts/apps.py, engage/contacts/views.py
Added a patch to override as_json so API responses only contain a subset of the extra data we are adding in to mailroom events. 
Fixed a bug that prevented the rapidpro ticket page from loading
None.
1. Create a flow with a `Open Ticket` event.
2. Send the flow to a contact
3. Navigate to contacts -> open tickets -> and click on the ticket. It should load.
=> PE-164 - Patcher to fix ticketing page

engage/flows/models.py, engage/utils/class_overrides.py
This should fix the button error.
=> PE-179: Flow> Archive> Check> Delete button errors out

temba/contacts/models.py
copy/paste an RP bugfix, tweak to include all triggers, not just active ones since we see in prod that even deleted triggers are still preventing deleting contact groups.
=> PE-317: delete trigger links when delete contact group.

engage/orgs/apps.py, engage/orgs/views/export.py
=> Fix Flow Export

engage/utils/middleware.py
=> Adjust exception handler to ignore RedirectTo exception
