- temba/urls.py
> P4 846 - Engage subdir error if empty string

- temba/channels/models.py
- temba/channels/types/bandwidth_international/views.py
- temba/orgs/models.py
- temba/orgs/views.py
- templates/channels/channel_read_list.haml
- templates/orgs/org_bandwidth_international_account.haml
https://istresearch.atlassian.net/browse/PULSE-7036
+ channel/org refactoring. 
To test:
Checkout repo and standup a rp-docker dev environment including postgres, ES, celery etc, but stop the engage service.
Run this engage branch from your pycharm ide connected to the services started from the rp-docker repo.
Once started, login and create a new bandwidth international channel. All credentials must be valid BWI credentials.
Once successful, navigate to the org home page and click on the "Connected to Bandwidth International..." link to expand the edit menu.
Ensure that the account id, username, sender and encoding type are all valid. The password field should be blank.
To edit the channel you must re-supply the valid password.
> PULSE 7036 - Channel/Org Refactoring

- temba/channels/types/bandwidth/views.py
- temba/orgs/models.py
- temba/orgs/views.py
- templates/orgs/org_bandwidth_account.haml
added messaging to prompt for E.164 formatting. also moving bwd configs to the channels instead of the org level.
> BWD - using channel configs instead of org level configs

- temba/middleware.py
- temba/urls.py
P4 713 - subdir value of None causes crashes in urls.py and in the middleware.py
> P4 713 - subdir value of None causes crashes

- temba/channels/types/telegram/type.py
- Add a telegram channel
- Visit config page for channel
- Enter value for "Forward ID"
- Save Changes
- Revisit config page, confirm value was saved
> adding forward_id to telegram channel config

- temba/channels/views.py
Minor fix for channel list page
> fix channel list link urls

- temba/channels/views.py
- temba/orgs/views.py
- add additional logic for sorting channels; in addition to roles DESC, adding sort by channel type (ASC) and then date added (ASC)
> P4-1022 - Change how we sort channels in home/list view

- static/coffee/flows/services.coffee
- temba/utils/fields.py
- templates/archives/archive_list.haml
- templates/contacts/contact_history.haml
- templates/contacts/contact_list.haml
- templates/contacts/contact_read.haml
- templates/contacts/contact_update_fields.haml
- templates/contacts/contactfield_list.haml
- templates/dashboard/home.haml
- templates/msgs/message_box.haml
- templates/policies/policy_admin.haml
- templates/utils/forms/completion_textarea.haml
- templates/utils/forms/contact_search.haml
- templates/utils/forms/omnibox_choice.haml
Fixing numerous erroneous URL paths.
> P4-1024 - fixing 404-error subdir paths

- temba/flows/views.py
Create a postmaster channel.
Navigate to a flow editor.
Click on a flow start node.
Select "Set preferred channel" from the drop down
The results should resemble this:
> Postmaster channel p4 1209

- templates/api/v2/api_root.html
- Adjusted  the prettify and codemirror css paths for the v2 api explorer.
> Fix static file urls for api explorer

- temba/channels/views.py
- temba/orgs/models.py
- temba/settings_common.py
- templates/channels/channel_manage.haml
- templates/channels/types/postmaster/config.haml
- templates/includes/nav.haml
- templates/orgs/org_postmaster_account.haml
new page: /channels/channel/manage/
It should provide a paginated list of all channels. Future releases will add additional features such as re-enable deleted(disabled) channels etc.
> P4-730 - Customize Channels Interface in Engage 4.0

- templates/orgs/org_bandwidth_international_connect.haml
the 
> All of these values can be found by logging into your ... 
text should be removed
> P4-1382 - We actually don't surface credentials via a Dashboard

- temba/flows/views.py
Simple PR, removes the "Surveyor" option from the Run Flow over section of the create flow form.
Removes the "Surveyor" option from the Run Flow section of the create flow form.
N/A
Simple PR, removes the "Surveyor" option from the Run Flow over section of the create flow form.
Create a flow, ensure that the Surveyor option is no longer present in the create flow form.
> P4-1483 - Hide Surveyor as Flow Option

- templates/channels/channel_manage.haml
1. The following columns were removed:
•“Created On” 
•“Modified On”
•“Urn Schemes”
2. These columns were renamed
•“Channel Type” to “Type”
•“Unique Identifier” to “UUID”
3. A new "Channel Log" column that links to the Channel's log page was added.
4. A new "Settings" column that links to the Channel's settings page was added.
5. The (+) add button was removed and replaced with a settings dropdown menu.
6. The default sort is based on the Channel creation date in descending order.
> Readding over-committed menu

- temba/channels/views.py
- temba/msgs/tests.py
> Master dev resolve

- temba/channels/types/postmaster/type.py
Fixes the Postmaster Channel edit form to support changing the channel name but not allow changing the mode or the device id. Also fixes the mode display to be correct.
Fixes the Postmaster Channel edit form.
3. Clean up with …
> Hotfix - Postmaster Channel Edit (master)

- package-lock.json
- package.json
- temba/ext/api/v2/views.py
Updated coffee and less in the npm package.json, adjusted the delete channel api endpoint to only return dependent flows' UUID and name. 
The delete channel endpoint will only return dependent flows' UUID and name, rather than full flow info. 
None.
1. Start up an engage 4.0.3-dev stack
2. Ensure you can access the web UI and all basic functionality works (to validate the coffee/less updates)
3. Create several postmaster channels from within the UI. 
4. Add at least one channel to a flow …
> P4-1606 - Adjust delete channel to return scoped flow data

- package-lock.json
- package.json
- temba/msgs/models.py
This PR is using a temporary branch for the floweditor. Please hold merge until floweditor is merged and tagged. 
Outgoing messages can be assigned labels from within the flow editor. 
Outgoing messages can be assigned labels from within the flow editor. 
None.
These changes are already deployed to the develop system
- Ensure old flows continue to open and work as expected. 
- Create a new flow with at least one "Send Message" action within the flow editor. Assign it at least one label.
- …
> P4-2303 - Labels for outgoing messages

- temba/api/v2/serializers.py
- temba/api/v2/views.py
P4-2441- Contact Endpoint - Add Ability to Set Channel
Add Ability to Set Channel via Contacts Endpoint: v2/contacts.json?uuid=
Add Ability to Set Channel via Contacts Endpoint: v2/contacts.json?uuid=
N/A
1. Standup Engage
2. Find the UUID of a contact that you would like to update
3. Perform a POST against `api/v2/contacts.json?uuid=UUID-From-Step-2` with a body of: `'{"channel":"channel-uuid-here"}'`
ex. 
```
curl  -vvv  -H "Content-Type: application/json" -H "Authorization: Token …
```
> feature/P4-2441 - Engage Contact Endpoint - Add Ability to Set Channel

- temba/channels/views.py
> P4-2737 - null Config prevents saving channel information

- temba/contacts/models.py
- temba/contacts/templatetags/contacts.py
- temba/settings_common.py
P4-2758 - Engage: Add new Postmaster channel for Email
Added new Postmaster channel for Email.
New Postmaster channel for Email.
None.
Build and Standup Engage running this branch.
Create a contact or navigate to an existing contact.
Edit the contact details and ensure that the new Identifier "Postmaster Email Identifier" is present.
Add the identifier and save.
Confirm that the icon shows up on the contacts view …
> P4-2758 - Engage: Add new Postmaster channel for Email

- temba/settings_common.py
> fixing no attribute PM_MESSENGER_SCHEME error

- package-lock.json
- package.json
> 4.0.9.2 - Bump flow editor to fix build issue

- temba/channels/types/postmaster/postoffice.py
Adjusted postoffice client to use new api format. 
Adjusted postoffice client to use new api format. 
None.
WIP
> P4-2862 - Use new postoffice api format.

- temba/msgs/views.py
> P4-2989 - Export Messages with ASYNC:off, display clickable link

- temba/settings_common.py
Disable PM last_seen sync task. 
N/A
None.
> P4-2990 - Disable PM last_seen sync task

- templates/msgs/message_box.haml
> P4-3189: Select All visible even when nothing to select.

- temba/channels/views.py
- templates/channels/channel_manage.haml
orig merge code buggy; fix channel page header sorting.
> fix channel page sorting

- temba/channels/views.py
- templates/channels/channel_manage.haml
fix bug in orig merge code and display sortable headers for channel list.
> fix channel list sorting

- docker/customizations/engage/templates/channels/channel_claim.haml
- docker/customizations/generic/templates/channels/channel_claim.haml
- templates/channels/channel_claim.haml
- templates/includes/nav.haml
> Removing android from channels claim page

- docker/customizations/engage/templates/channels/channel_claim.haml
- docker/customizations/generic/templates/channels/channel_claim.haml
- templates/channels/channel_claim.haml
- templates/includes/nav.haml
> Channels remove android

- temba/flows/views.py
> Export flow context menu links is shown multiple times

- temba/orgs/views.py
> P4 3363 bwd imports

- docker/customizations/engage/templates/channels/channel_claim.haml
- docker/customizations/generic/templates/channels/channel_claim.haml
recommends only PM; removes BWI and Android Phone types.
recommends only PM; removes BWI and Android Phone types.
None.
> P4-3372: recommends only PM; removes BWI and Android Phone types.

- docker/customizations/any/static/fonts/style.css
- docker/customizations/any/templates/channels/channel_read.haml
- docker/customizations/engage/temba/settings.py
- docker/customizations/generic/temba/settings.py
- temba/channels/types/postmaster/views.py
- templates/channels/types/postmaster/claim.haml
Add ENV vars that, if present, will show a QR code to download the PM app associated with its instance.
Postmaster Channel claim code page now includes a link and QR code for downloading the appropriate app.
None.
> P4-3389: add a configurable PM dl link/qrcode to PM claim page.

- .circleci/config.yml
> circleci: dev deploy should specify image tag.

- docker/customizations/any/static/less/refresh.less
- docker/customizations/any/temba/channels/views.py
- docker/customizations/any/templates/channels/channel_read.haml
- temba/channels/types/postmaster/views.py
- templates/channels/types/postmaster/claim.haml
> P4-3389: tweak js/css so FF will work with PM dl qrcode.

- docker/customizations/engage/static/brands/engage/less/engage.less
Logout menu fixed so it is not hidden behind page elements.
Logout menu fixed so it is not hidden behind page elements.
None.
ensure this does _NOT_ happen:
> header: menu: fix z-index order.

- temba/channels/types/postmaster/type.py
> P4-3430 - Engage - 500 error when editing (saving) channel

- docker/Dockerfile.rp
> circleci: fix build.

- docker/customizations/any/temba/channels/models.py
> Feature/p4 3462 Make allow international True by default

- engage/hamls/msgs/message_box.haml
- engage/static/engage/js/msg-message_box-update.js
> js cannot handle {% %}, move to haml.

- docker/customizations/any/temba/msgs/models.py
- engage/hamls/msgs/msg_failed.haml
- engage/msgs/inbox_msgfailed.py
- engage/static/engage/js/msg-message_box.js
- engage/utils/overrides.py
- temba/msgs/cto.py
Delete button restored to Failed Inbox along with confirmation dialog when deleting Failed messages.
Delete button restored to Failed Inbox along with confirmation dialog when deleting Failed messages.
None.
Delete button in Failed Messages area should now be visible and work correctly to delete a single or a set of Failed messages selected.  The Delete button should pop up a secondary dialog asking for confirmation before actually deleting anything.  Archive of Failed messages is …
> P4-3592: re-add Delete into Msg Inbox for Failed msgs

- engage/archives/models.py
- engage/channels/models.py
- engage/contacts/models.py
- engage/msgs/models.py
Delete Archive message button works again.
Delete Archive message button works again.
None.
1. Go to Messages page
2. Select Archived messages, if any, else you need to archive a message to create one to work with.
3. Check the box of a message to delete
4. Click the Delete button and wait a second or three for the message to disappear from the list.
> P4-4132: Delete Archived Msg not working

- engage/channels/manage.py
- engage/channels/models.py
- engage/channels/types/vonage_client.py
- engage/channels/types/vonage_views.py
- engage/channels/views.py
- engage/hamls/channels/channel_claim_number.haml
- engage/hamls/orgs/user_list.haml
- engage/msgs/views/inbox.py
- engage/orgs/models.py
- engage/orgs/views/user_delete.py
- engage/orgs/views/user_list.py
- engage/static/engage/less/engage.less
- engage/utils/middleware.py
- engage/utils/overrides.py
- scm/utils.sh
- temba/settings_engage.py
Channel delete redirects to the Manage Channel list rather than org home page, complete with search criteria based on the current session.
Channel delete redirects to the Manage Channel list rather than org home page, complete with search criteria based on the current session.
None.
1. Channels page (Manage Channels)
2. Search for a set of PM channels
3. View the Channel Log of one of the PM channels
4. Click the name/link to get to the channel details page where Purge Outbox and Delete …
> P4-4196: channel delete redirects to manage channel list

- engage/channels/models.py
- engage/channels/types/vonage_client.py
- engage/channels/types/vonage_views.py
- engage/hamls/channels/channel_claim_number.haml
- engage/static/engage/less/engage.less
- engage/utils/overrides.py
Show the "in use" status of aggregators that have many phone numbers listed so you don't have to guess what is in use or not.
> Show Aggregator Phone "in use" status

- .github/workflows/build-image-layer1.yml
- .github/workflows/build-image-layer2.yml
- .github/workflows/build-image-layer3.yml
- .github/workflows/build-image-layer4.yml
- .github/workflows/build-image-result.yml
- .github/workflows/util-docker-image-exists.yml
- pyproject.toml
> GitHub Actions debuggged

- .github/workflows/build-image-layer3.yml
- .gitignore
> gha: fix lack of 'ci-develop' version tag.

- .github/workflows/build-image-layer3.yml
> gha: layer 3 versioning develop fixed tag.

- .github/workflows/build-image-layer2.yml
- .github/workflows/build-image-layer3.yml
- .github/workflows/build-image-layer4.yml
> gha: merge in all dev work from dev/PE-25 that applies for gha.

- engage/auth/account.py
- engage/channels/models.py
- engage/channels/purge_outbox.py
- engage/contacts/views.py
- engage/hamls/frame.haml
- engage/hamls/msgs/msg_read.haml
- engage/msgs/apps.py
- engage/msgs/models.py
- engage/msgs/views/read.py
- engage/orgs/models.py
- temba/settings_engage.py
- templates/api/v2/api_root.html
> register/unregister fixes mostly.

- engage/hamls/msgs/message_box.haml
- engage/hamls/msgs/msg_read.haml
- engage/msgs/views/read.py
> improve msg_read page.

- engage/contacts/views.py
- temba/contacts/views.py
> fix discovered bugs

- temba/settings_engage.py
perform an export, then try to download the export
> reduce s3 query expire as required.

- engage/hamls/flows/flow_editor.haml
Made a small tweak to a path used in the flow editor haml so it uses the correct path for recent contacts.
Recent contacts will now correctly appear in the flow editor.
None.
1. Create a flow within engage
2. Sent it to a contact
3. After a few seconds ensure the contact appears on the flow editor
> Fix invalid recent contact path

- engage/api/responses.py
- engage/channels/types/postmaster/apks.py
- temba/settings_engage.py
- workspace/docker-compose.yml
- Added app name to PG connections in the working compose file
- Add DATABASE_CONN_MAX_AGE (default 60) env var to control how long connections stay. 
N/A
None.
1. `docker-compose up -d `
2. Go into PG and run `SELECT * FROM pg_stat_activity;`, ensure all the engage apps have an app name listed.
> PE-174: Add app name to connections, add optional DATABASE_CONN_MAX_AGE setting

- engage/api/exceptions.py
- engage/flows/models.py
- engage/utils/class_overrides.py
> PE-179: fix delete archive flows

- engage/channels/views.py
Add org perm check to channel override so it correctly redirects if it is a different org. 
None
> Add org perm check to channel override

- engage/hamls/orgs/org_manage_accounts.haml
- engage/orgs/apps.py
- engage/orgs/views/manage_accounts.py
- temba/settings_engage.py
> PE-173: superadmin: disable invite user when SEND_EMAIL is off.

- engage/auth/account.py
- engage/auth/apps.py
- engage/channels/views.py
- engage/contacts/views.py
- engage/msgs/views/read.py
- engage/orgs/views/user_assign.py
> redirect linkage should check if anon user first.

- engage/hamls/flows/flow_list.haml
haml updated to use UUID instead of pk ID as needed by new flow code.
> PE-189: view Flows list by a label gives 502 

- engage/campaigns/apps.py
- engage/campaigns/models.py
- engage/campaigns/views.py
- engage/hamls/campaigns/campaign_list.haml
- engage/hamls/flows/flow_list.haml
- engage/static/engage/js/delete-content.js
- temba/settings_engage.py
add Delete archived campaigns (Scenario) feature to list of actions you can apply to a selected (checked) Scenario.
> PE-212: delete campaigns

- engage/api/apps.py
- engage/api/views.py
> broadcast api endpoint documentation update/fix.

- engage/channels/types/postmaster/schemes.py
> Fix mismatch between service and scheme

- engage/channels/apps.py
- engage/channels/types/postmaster/schemes.py
- engage/static/engage/less/engage.less
- temba/channels/types/postmaster/views.py
- temba/ext/api/v2/views.py
> simplify custom pm scheme definition.

- engage/hamls/channels/channelevent_calls.haml
- engage/hamls/msgs/message_box.haml
- engage/orgs/views/user_assign.py
- engage/static/engage/less/engage.less
- engage/static/engage/less/frame.less
> PE-193: change "error" messages on webpage to RED instead of white.

- engage/api/apps.py
- engage/api/serializers.py
> PE-203: flow_start needs to also respect max msg length setting.

- engage/contacts/models.py
- engage/hamls/msgs/message_box.haml
- engage/static/engage/less/engage.less
> detect and color PM contact

- engage/contacts/models.py
> PE-245: too many params bugfix.

- engage/api/serializers.py
- engage/api/support.py
- engage/channels/models.py
- engage/channels/purge_outbox.py
- engage/channels/views.py
- engage/contacts/models.py
- engage/contacts/views.py
- engage/flows/views.py
- engage/hamls/channels/channel_read.haml
- engage/hamls/msgs/msg_outbox.haml
- engage/msgs/apps.py
- engage/msgs/views/inbox.py
- engage/msgs/views/outbox.py
- engage/orgs/models.py
- engage/orgs/views/home.py
- engage/orgs/views/manage_accounts.py
- engage/orgs/views/sub_orgs.py
- engage/orgs/views/user_list.py
- engage/static/engage/js/frame-common.js
- engage/static/engage/js/frame-ready.js
- engage/utils/class_overrides.py
> PE-208: purge outbox button added

- engage/api/apps.py
- engage/api/serializers.py
- engage/api/views.py
- engage/contacts/models.py
> PE-256: add channels prop to Contacts & return it via API.

- engage/hamls/frame.haml
- engage/hamls/pm/read.haml
- engage/pm/view/read.py
- engage/static/engage/js/frame-ready.js
- engage/static/engage/js/geo-loc.js
- package-lock.json
- package.json
- temba/settings_engage.py
> add Map Libs; focus static file builds to just libs we need.

- engage/flows/models.py
> Fix bug with new flow creation

- engage/api/apps.py
- engage/api/endpoint/messages.py
> msg endpoint: update send_on help text.

- engage/contacts/views.py
> PE-299: contacts list sort nulls last, always.

- engage/api/endpoint/messages.py
- engage/contacts/views.py
add line about deprecated `media` key
> PE-304: update msg endpoint help text

- engage/flows/view/editor.py
- engage/hamls/flows/flow_editor.haml
- engage/hamls/gear_links_include.haml
- engage/static/engage/js/flow-editor.js
- engage/static/engage/js/frame-common.js
Pan/Zoom feature added to flow editor.
Buttons can now have tooltips (Re-center button's tooltip shows how feature works).
> floweditor: add pan/zoom feature.

- engage/contacts/views.py
specialized SQL required instead of searching ES for contact info.
> PE-319: child table requires very funky SQL to sort on.

- engage/channels/views.py
- engage/hamls/channels/channel_read.haml
- engage/static/engage/js/flow-editor.js
- temba/channels/views.py
URNs may still hold on to inactive channels, display as 'INACTIVE'.
> PE-312: display inactive channels with noticeable flag.

- engage/contacts/views.py
> PR-348 - Don't grab system fields for contact sort magic.

- engage/channels/manage.py
- engage/hamls/channels/types/postmaster/config.haml
- engage/hamls/flows/flow_editor.haml
- engage/pm/templatetags/pm.py
- engage/pm/view/read.py
- engage/static/engage/js/broadcast_send.js
Removed incorrect text from settings page for PSM, adjusted settings link to go to the PM page when clicked.
> PE-350 - Clean up channel manage page for PM

- engage/contacts/apps.py
- engage/contacts/views.py
- temba/contacts/views.py
> PE-362 - Remove contact 200 page limit

- engage/flows/view/simulate.py
> Fix tel simulator error

- engage/channels/models.py
- engage/channels/types/postmaster/schemes.py
- engage/hamls/channels/channel_read.haml
- engage/hamls/contacts/contact_read.haml
- engage/hamls/pm/list.haml
- engage/hamls/pm/read.haml
- engage/pm/templatetags/pm.py
- engage/pm/view/read.py
- temba/channels/migrations/013902_pm_services.py
- temba/settings_engage.py
remove chat_mode from channel meta; link channel subtitle to device page.
> chat_mode-b-gone; link parent pm_service page in channel page
